version: '3.8'

services:
  java-api:
    build: .
    container_name: urlshortener
    ports:
      - "8080:8080"
      #- "9229:9229" #debug port
    depends_on:
      - redis
      - rdbms
    # restart: unless-stopped
    environment:
      #JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9229"  # Enable remote debugging
      REDIS_HOST: "redis"
      SPRING_DATASOURCE_URL: jdbc:postgresql://rdbms:5432/upworkdatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_PROFILES_ACTIVE: "docker"
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

  rdbms:
    image: 'postgres:latest'
    container_name: rdbms
    environment:
      - 'POSTGRES_DB=upworkdatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    networks:
      - my-network  

networks:
  my-network:
    driver: bridge