services:
  java-api:
    build: .
    container_name: urlshortener
    ports:
      - "8081:8081"
      - "9229:9229" #debug port
    depends_on:
      - redis
      - db
    # restart: unless-stopped
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9229"  # Enable remote debugging
      REDIS_HOST: "redis"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/upworkdatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_PROFILES_ACTIVE: "docker"
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=upworkdatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    networks:
      - my-network  

networks:
  my-network:
    driver: bridge